### ISSUE TITLE
workflow解析不出来

### ISSUE THREAD

**Issue by Devmber** [xingren23/ComfyFlowApp#22]
在Creator模式下，上传工作流图片上去的时候，显示图片里没有工作流信息是为什么？

**Comment by xingren23** [comment]
please check image has prompt meta data, eg:

<img width="1435" alt="image" src="https://github.com/xingren23/ComfyFlowApp/assets/3837202/030a70f8-3c69-475c-846f-c9b6d7022dfe">

**Comment by xingren23** [comment]
ComfyUI workflow Image > Export > png, only include workflow meta, but not include prompt meta, so the image could load in comfyui，but could not load in comfyflowapp。

**Comment by DreamStudio2015** [comment]
> ComfyUI workflow Image > Export > png, only include workflow meta, but not include prompt meta, so the image could load in comfyui，but could not load in comfyflowapp。

Yeah，that is the issue. But how to get the correct image?

**Comment by DreamStudio2015** [comment]
> > ComfyUI workflow Image > Export > png, only include workflow meta, but not include prompt meta, so the image could load in comfyui，but could not load in comfyflowapp。
> 
> Yeah，that is the issue. But how to get the correct image?

When the workflow png was exported by "ComfyUI workflow Image > Export > png",  then one need to transform the png by "load the png" > "save the png", and then get the right png in Output folder.
