### ISSUE TITLE
https://api.comfyflow.app不能访问

### ISSUE THREAD

**Issue by GuoYangGit** [xingren23/ComfyFlowApp#49]
connect to comfyui node error, HTTPConnectionPool(host='localhost', port=8188): Max retries exceeded with url: /object_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028EC094A090>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by xingren23** [comment]
" connect to comfyui node error, "

you should check your comfyui instance is up
