### ISSUE TITLE
'streamlit' is not recognized

### ISSUE THREAD

**Issue by aegis72** [xingren23/ComfyFlowApp#6]
"H:\ComfyFlowApp\bin>run.bat
'streamlit' is not recognized as an internal or external command,
operable program or batch file."

Cloned repo and ran pip + set server, but get the above.

In the install folder, my file list is as follows:
![image](https://github.com/xingren23/ComfyFlowApp/assets/118572301/161a2747-572e-45c8-8a80-0019a2174272)

Any ideas?

**Comment by xingren23** [comment]
Thank you for trying out ComfyFlowApp.

It's possible that Streamlit was not installed successfully. You can check if there were any error messages when running "pip install -r requirements.txt." After a successful installation, you can run "streamlit version" to verify.

PS E:\ComfyFlowApp> pip install -r .\requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
。。。。
PS E:\ComfyFlowApp> streamlit version
Streamlit, version 1.27.2

**Comment by aegis72** [comment]
I'll take a look in a bit once I can switch to my non-work dev environment. Thanks!
