### ISSUE TITLE
How to upload .mp4 file?

### ISSUE THREAD

**Issue by hiowenluke** [xingren23/ComfyFlowApp#66]
The node video-uploader is below:

<img width="321" alt="image" src="https://github.com/xingren23/ComfyFlowApp/assets/19872828/9bf7d47a-0fc6-465a-b9cd-968505c5f333">

When I chose it as input, I can not see the video upload button:

<img width="558" alt="image" src="https://github.com/xingren23/ComfyFlowApp/assets/19872828/d0485aa1-3839-430a-be5f-c568822633ae">

And there is no way to upload video files when the app running:

<img width="602" alt="image" src="https://github.com/xingren23/ComfyFlowApp/assets/19872828/1719b334-6813-49ef-889c-b64110162a02">

Is there something I missed?

**Comment by xingren23** [comment]
Sorry, uploading videos is not supported yet. I will update it when I have time, maybe this week.

**Comment by hiowenluke** [comment]
Thank you.

**Comment by xingren23** [comment]
now support to upload video, mp4 or h264
https://github.com/xingren23/ComfyFlowApp/commit/c4d26a4ac307e01db0498207c51a58bfe2d638e9
