### ISSUE TITLE
[Optional] [Readability problem]Wrong variable name

### ISSUE THREAD

**Issue by Fourth-fresh-man** [xingren23/ComfyFlowApp#67]
it should be table not that talbe🙂. 
![sc1](https://github.com/xingren23/ComfyFlowApp/assets/41275436/97fe46fc-1357-4f1a-9658-b3c05c4ced38)

**Comment by xingren23** [comment]
thanks, i will check it

**Comment by xingren23** [comment]
fixed it, thanks 
https://github.com/xingren23/ComfyFlowApp/commit/720f88388f2a7a1c1234a2820c3fe0f9f6ff3326
