### ISSUE TITLE
OperationalError: (sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by huanyingtianhe** [xingren23/ComfyFlowApp#70]
OperationalError: (sqlite3.OperationalError) database is locked [SQL: CREATE TABLE IF NOT EXISTS comfyflow_apps (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, image TEXT, app_conf TEXT, api_conf TEXT, template TEXT, url TEXT, status TEXT, created_at TEXT, updated_at TEXT);] (Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by xingren23** [comment]
This issue often occurs because the database is locked by another process. Try restarting your application or waiting for a bit before attempting to access the database again.
